### ISSUE TITLE
mysql is unavailable - retry 1s

### ISSUE THREAD

**Issue by kexuebiao** [FlowCI/docs#10]
安装后一直无法使用
flow.ci_1   | Starting MariaDB database server: mysqld . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . failed!
flow.ci_1   | mysql is unavailable - retry 1s

**Comment by yunheli** [comment]
@kexuebiao 统一在docker项目的issue里回复你，这个先关了

**Comment by yunheli** [comment]
问题已解决可以关闭，由于机器资源有限导致初始化mysql buffer失败
