### ISSUE TITLE
基于 Linux 的安装

### ISSUE THREAD

**Issue by lluxury** [FlowCI/docs#11]
在基于 Linux 的安装一节中,需要配置 app-api.properties及app-cc.properties, git克隆下的文件中,
app-api.properties写到
### domain ###
domain.api = http://localhost:8080
domain.web = http://localhost:3000
domain.cc = http://localhost:8080

app-cc.properties写到
### agent config ###
agent.config.ws = ws://localhost:8088
agent.config.cc = http://localhost:8080

但文件说明又说agent.config.ws: 配置 Websocket 的地址，必须以 ws 开头，和 API 中 domain.api 的域名一致,请问是哪一边写错了. 8088,还是8080

**Comment by yunheli** [comment]
@lluxury  端口 8080

**Comment by yunheli** [comment]
## flow api config file ##

### JDBC config ###
jdbc.url = jdbc:mysql://127.0.0.1:3306/flow_api_db?useSSL=false
jdbc.username = db_username
jdbc.password = db_password
jdbc.pool.size = 50
jdbc.commit.auto = false
jdbc.connection.timeout = 20000

### Hibernate config ###
hibernate.show_sql = false
hibernate.hbm2ddl.auto = validate

### api settings ###
api.workspace = ${HOME}/flow-ci/workspace
api.git.cache = ${HOME}/flow-ci/git-cache
api.git.workspace = ${HOME}/flow-ci/git-repos
api.zone.default = default

### expiration duration of token, it's in millisecond ###
### 86400000 = 1000 * 60 * 60 * 24 = 1 day (will expiration after one day) ###
api.user.expire = 86400000

### domain ###
domain.api = http://api_domain:8080/flow-api
domain.web = http://web_domain:3000
domain.cc = http://api_doamin:8080/flow-control-center

system.email = admin@flow.ci
system.username = admin
system.password = 123456

## plugin repos url
plugins.repository = https://raw.githubusercontent.com/flowci/plugins/master/repository.json

task.job.toggle.execution_timeout = true
## expired in 1800 seconds for create session
task.job.toggle.execution_create_session_duration = 1800
## expired in 3600 seconds for job running
task.job.toggle.execution_running_duration = 3600

**Comment by yunheli** [comment]
@lluxury 改一下配置文件

**Comment by yunheli** [comment]
### agent config ###
agent.config.ws = ws://api_domain:8080/flow-api
agent.config.cc = http://api_domain:8080/flow-control-center

**Comment by lluxury** [comment]
收到,多谢

**Comment by lluxury** [comment]
再请问一下:
导入配置文件并启动
安装 dist 目录下的 flow-api-.war 以及 flow-control-center-.war 到 Apache Tomcat 服务器中，并设置上一步配置的 app-api.properties 到 FLOW_API_CONFIG_PATH 环境变量，app-cc.properties 到 FLOW_CC_CONFIG_PATH 环境变量

配置的 app-api.properties到 FLOW_API_CONFIG_PATH 环境变量需要怎么操作?

**Comment by yunheli** [comment]
@lluxury  把配置文件copy到  /etc/flow.ci/config文件夹下，没有的话创建一个

**Comment by yunheli** [comment]
export FLOW_API_CONFIG_PATH=/etc/flow.ci/config
