### ISSUE TITLE
ERROR 1293 (HY000) at line 3: Incorrect table definition; there can be only one TIMESTAMP column with CURRENT_TIMESTAMP in DEFAULT or ON UPDATE clause

### ISSUE THREAD

**Issue by armolee** [FlowCI/docs#12]
？

**Comment by armolee** [comment]
mysql -u root -p --database=flow_api_db < schema/flow_api_db.sql

**Comment by yang-guo-2016** [comment]
@armolee 您的 MYSQL 版本是多少？ flow.ci 目前只支持 5.6+ 的版本

**Comment by armolee** [comment]
在5.5创建的表，无法导入升级到了10.1还是无法导入，需要重新创建表吗？用的mariadb

**Comment by yang-guo-2016** [comment]
无法导入是什么错误 ？ flow.ci 的 Docker 镜像里面用的是 mariadb，从新创建下数据库，之后再试下
