### ISSUE TITLE
macOS上使用docker部署，默认的admin与密码登录不上

### ISSUE THREAD

**Issue by Neojoke** [FlowCI/docs#19]
![snipaste_2018-01-26_18-28-58](https://user-images.githubusercontent.com/8511328/35435752-d731e324-02c6-11e8-8ea4-38955b35f1a9.png)
admin 登录无反应

**Comment by Neojoke** [comment]
flow.ci_1   | 2018-01-26 10:26:25.243 [TRACE] JobService - job timeout task start
flow.ci_1   | 2018-01-26 10:26:25.246 [TRACE] JobService - job timeout task end
flow.ci_1   | 2018-01-26 10:26:44.530 [TRACE] AgentService:sessionTimeoutTask - start
flow.ci_1   | 2018-01-26 10:26:44.534 [TRACE] AgentService:sessionTimeoutTask - end
flow.ci_1   | 2018-01-26 10:27:25.248 [TRACE] JobService - job timeout task start
flow.ci_1   | 2018-01-26 10:27:25.252 [TRACE] JobService - job timeout task end
flow.ci_1   | 2018-01-26 10:27:44.535 [TRACE] AgentService:sessionTimeoutTask - start
flow.ci_1   | 2018-01-26 10:27:44.538 [TRACE] AgentService:sessionTimeoutTask - end
flow.ci_1   | 2018-01-26 10:28:25.254 [TRACE] JobService - job timeout task start
flow.ci_1   | 2018-01-26 10:28:25.258 [TRACE] JobService - job timeout task end
flow.ci_1   | 2018-01-26 10:28:35.696 [TRACE] CmdDispatchService:checkTimeoutTask - start
flow.ci_1   | 2018-01-26 10:28:35.701 [TRACE] CmdDispatchService:checkTimeoutTask - end
flow.ci_1   | 2018-01-26 10:28:44.539 [TRACE] AgentService:sessionTimeoutTask - start
flow.ci_1   | 2018-01-26 10:28:44.545 [TRACE] AgentService:sessionTimeoutTask - end
flow.ci_1   | 2018-01-26 10:29:25.261 [TRACE] JobService - job timeout task start
flow.ci_1   | 2018-01-26 10:29:25.264 [TRACE] JobService - job timeout task end
flow.ci_1   | 2018-01-26 10:29:44.546 [TRACE] AgentService:sessionTimeoutTask - start
flow.ci_1   | 2018-01-26 10:29:44.552 [TRACE] AgentService:sessionTimeoutTask - end

**Comment by cutephp** [comment]
建议使用docker ps查看后端服务是否起来了 我之前在服务器上面因为内存原因没有启动 你再检查一下给docker分配了多少内存 建议最少4G

**Comment by Neojoke** [comment]
@cutephp 因为要构建iOS端的项目，所以要在mac平台上搭建flowci，一个jenkins才需要800多m，这个竟然要4G？还是不玩了，docker的默认参数也不知道为什么不用ENV设置，写了一个shell脚本，打开才知道里面就是使用了一下dock-compose，为什么没有把docker hub上的几个镜像解释清楚，出问题了也不知道是哪里的。。。。。目测也就我反馈问题了，看来基本上没啥人用。。。。

**Comment by Neojoke** [comment]
flowci/flow-platform:latest 容器使用8080端口，被占用了，现在好了。
