### ISSUE TITLE
docker_flow.ci_1 exited with code 143

### ISSUE THREAD

**Issue by MagicMashRoom** [FlowCI/docs#21]
请问有没有错误码对照表
 还有 项目支持账号的多端登陆吗

**Comment by yunheli** [comment]
@MagicMashRoom 报什么错误，截个图？把启动的详细步骤发一下

**Comment by MagicMashRoom** [comment]
$ ./start-services.sh
##############Start Update Docker Images###################
latest: Pulling from flowci/flow-platform
Digest: sha256:6e7a8a0f33f9272c9df595e91a2f16825896946fd6124d250147d47926583119
Status: Image is up to date for flowci/flow-platform:latest
latest: Pulling from flowci/flow-web
Digest: sha256:ebec006624dc5660305bb66b08ecdf6ea4c9d516e376cae57bdad70e40244890
Status: Image is up to date for flowci/flow-web:latest
##############Finish Update Docker Images###################
###########环境变量说明###########
MYSQL_USER: 配置的Mysql的初始用户名, 默认是 root , 不可修改
JVM 最大堆大小为 1.5G
Mysql 的 默认存储路径是 /c/Users/dafengluo/data/flowci/mysql , 假如您正式部署请选择正确的配置路径
MYSQL_PASSWORD: 配置的Mysql的初始密码, 默认是 flow.ci , 当前参数是 flow.ci
MYSQL_HOST: 配置的Mysql的HOST地址, 默认是 127.0.0.1 , 当前参数是 127.0.0.1
FLOW_API_DOMAIN: 部署的FlowApi地址, 默认是 127.0.0.1, 当前参数值是 127.0.0.1
FLOW_WEB_DOMAIN: 部署的FlowWeb地址, 默认是 127.0.0.1, 当前参数值是 127.0.0.1
FLOW_SYS_EMAIL: Flow 的系统账号， 默认是 admin@flow.ci, 当前参数值是 admin@flow.ci
FLOW_SYS_USERNAME: Flow 的系统用户名， 默认是 admin, 当前参数值是 admin
FLOW_SYS_PASSWORD: Flow 的系统密码， 默认是 123456, 当前参数值是 123456
Starting docker_flow.ci_1 ... done
Starting docker_flow.web_1 ... done
Attaching to docker_flow.ci_1, docker_flow.web_1
flow.ci_1   | Starting MariaDB database server: mysqld ..
flow.ci_1   | mysql is up
flow.ci_1   | ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: NO)
flow.ci_1   | running migration
flow.ci_1   | Flyway 4.2.0 by Boxfuse
flow.ci_1   |
flow.ci_1   | Database: jdbc:mysql://127.0.0.1:3306/flow_api_db (MySQL 10.1)
flow.ci_1   | Successfully validated 3 migrations (execution time 00:00.026s)
flow.ci_1   | Current version of schema `flow_api_db`: 1.3
flow.ci_1   | Schema `flow_api_db` is up to date. No migration necessary.
flow.ci_1   | Flyway 4.2.0 by Boxfuse
flow.ci_1   |
flow.ci_1   | Database: jdbc:mysql://127.0.0.1:3306/flow_cc_db (MySQL 10.1)
flow.ci_1   | Successfully validated 2 migrations (execution time 00:00.018s)
flow.ci_1   | Current version of schema `flow_cc_db`: 1.1
flow.ci_1   | Schema `flow_cc_db` is up to date. No migration necessary.
flow.ci_1   | finish migration
flow.ci_1   | Starting Docker: docker.
flow.ci_1   | 26-Feb-2018 06:56:32.205 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server version:        Apache Tomcat/8.5.16
flow.ci_1   | 26-Feb-2018 06:56:32.208 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server built:          Jun 21 2017 17:01:09 UTC
flow.ci_1   | 26-Feb-2018 06:56:32.208 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server number:         8.5.16.0
flow.ci_1   | 26-Feb-2018 06:56:32.209 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log OS Name:               Linux
flow.ci_1   | 26-Feb-2018 06:56:32.209 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log OS Version:            4.9.60-linuxkit-aufs
flow.ci_1   | 26-Feb-2018 06:56:32.209 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Architecture:          amd64
flow.ci_1   | 26-Feb-2018 06:56:32.209 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Java Home:             /usr/lib/jvm/java-8-openjdk-amd64/jre
flow.ci_1   | 26-Feb-2018 06:56:32.210 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log JVM Version:           1.8.0_151-8u151-b12-1~deb9u1-b12
flow.ci_1   | 26-Feb-2018 06:56:32.210 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log JVM Vendor:            Oracle Corporation
flow.ci_1   | 26-Feb-2018 06:56:32.210 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log CATALINA_BASE:         /usr/local/tomcat
flow.ci_1   | 26-Feb-2018 06:56:32.210 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log CATALINA_HOME:         /usr/local/tomcat
flow.ci_1   | 26-Feb-2018 06:56:32.211 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.util.logging.config.file=/usr/local/tomcat/conf/logging.properties
flow.ci_1   | 26-Feb-2018 06:56:32.212 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager
flow.ci_1   | 26-Feb-2018 06:56:32.212 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djdk.tls.ephemeralDHKeySize=2048
flow.ci_1   | 26-Feb-2018 06:56:32.212 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.protocol.handler.pkgs=org.apache.catalina.webresources
flow.ci_1   | 26-Feb-2018 06:56:32.213 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Xms1536m
flow.ci_1   | 26-Feb-2018 06:56:32.213 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Xmx1536m
flow.ci_1   | 26-Feb-2018 06:56:32.214 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcatalina.base=/usr/local/tomcat
flow.ci_1   | 26-Feb-2018 06:56:32.214 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcatalina.home=/usr/local/tomcat
flow.ci_1   | 26-Feb-2018 06:56:32.214 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.io.tmpdir=/usr/local/tomcat/temp
flow.ci_1   | 26-Feb-2018 06:56:32.215 INFO [main] org.apache.catalina.core.AprLifecycleListener.lifecycleEvent Loaded APR based Apache Tomcat Native library [1.2.12] using APR version [1.5.2].
flow.ci_1   | 26-Feb-2018 06:56:32.215 INFO [main] org.apache.catalina.core.AprLifecycleListener.lifecycleEvent APR capabilities: IPv6 [true], sendfile [true], accept filters [false], random [true].
flow.ci_1   | 26-Feb-2018 06:56:32.215 INFO [main] org.apache.catalina.core.AprLifecycleListener.lifecycleEvent APR/OpenSSL configuration: useAprConnector [false], useOpenSSL [true]
flow.ci_1   | 26-Feb-2018 06:56:32.227 INFO [main] org.apache.catalina.core.AprLifecycleListener.initializeSSL OpenSSL successfully initialized [OpenSSL 1.1.0f  25 May 2017]
flow.ci_1   | 26-Feb-2018 06:56:32.349 INFO [main] org.apache.coyote.AbstractProtocol.init Initializing ProtocolHandler ["http-nio-8080"]
flow.ci_1   | 26-Feb-2018 06:56:32.507 INFO [main] org.apache.tomcat.util.net.NioSelectorPool.getSharedSelector Using a shared selector for servlet write/read
flow.ci_1   | 26-Feb-2018 06:56:32.521 INFO [main] org.apache.coyote.AbstractProtocol.init Initializing ProtocolHandler ["ajp-nio-8009"]
flow.ci_1   | 26-Feb-2018 06:56:32.522 INFO [main] org.apache.tomcat.util.net.NioSelectorPool.getSharedSelector Using a shared selector for servlet write/read
flow.ci_1   | 26-Feb-2018 06:56:32.523 INFO [main] org.apache.catalina.startup.Catalina.load Initialization processed in 906 ms
flow.ci_1   | 26-Feb-2018 06:56:32.618 INFO [main] org.apache.catalina.core.StandardService.startInternal Starting service [Catalina]
flow.ci_1   | 26-Feb-2018 06:56:32.619 INFO [main] org.apache.catalina.core.StandardEngine.startInternal Starting Servlet Engine: Apache Tomcat/8.5.16
flow.ci_1   | 26-Feb-2018 06:56:32.836 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployWAR Deploying web application archive [/usr/local/tomcat/webapps/flow-control-center.war]
flow.ci_1   | 26-Feb-2018 06:56:35.969 INFO [localhost-startStop-1] org.apache.jasper.servlet.TldScanner.scanJars At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
flow.ci_1   | 2018-02-26 06:56:36.359 [TRACE] AppInit - Initializing Flow Control Center for Apache Tomcat/8.5.16
flow.ci_1   | log4j:WARN No appenders could be found for logger (org.springframework.web.context.support.StandardServletEnvironment).
flow.ci_1   | log4j:WARN Please initialize the log4j system properly.
flow.ci_1   | log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
flow.ci_1   | 2018-02-26 06:56:38.332 [TRACE] QueueConfig - Host: amqp://localhost:5672
flow.ci_1   | 2018-02-26 06:56:38.333 [TRACE] QueueConfig - Management Host: http://localhost:15672
flow.ci_1   | 2018-02-26 06:56:38.333 [TRACE] QueueConfig - Cmd queue name: flow-cmd-queue-default
flow.ci_1   | 2018-02-26 06:56:38.334 [TRACE] QueueConfig - Cmd RabbitMQ enabled: false
flow.ci_1   | 2018-02-26 06:56:38.334 [TRACE] QueueConfig - Cmd queue retry enabled: false
flow.ci_1   | SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
flow.ci_1   | SLF4J: Defaulting to no-operation (NOP) logger implementation
flow.ci_1   | SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
flow.ci_1   | 2018-02-26 06:56:41.305 [TRACE] QueueConfig - Apply in memory queue for cmd queue
flow.ci_1   | 2018-02-26 06:56:41.338 [TRACE] ZooKeeper - Host: 127.0.0.1:2181
flow.ci_1   | 2018-02-26 06:56:41.339 [TRACE] ZooKeeper - Root node: flow-agents
flow.ci_1   | 2018-02-26 06:56:41.340 [TRACE] ZooKeeper - Zones: default
flow.ci_1   | 2018-02-26 06:56:41.341 [TRACE] ZooKeeper - Embedded enabled: true
flow.ci_1   | 2018-02-26 06:56:41.361 [INFO ] ZooKeeper - Starting internal zookeeper server.......
flow.ci_1   | 2018-02-26 06:56:41.653 [INFO ] ZooKeeper - Client been connected at: 127.0.0.1:2181
flow.ci_1   | 2018-02-26 06:56:41.676 [TRACE] TaskConfig - Zone.Toggle.KeepIdleAgent: false
flow.ci_1   | 2018-02-26 06:56:41.677 [TRACE] TaskConfig - Agent.Toggle.SessionTimeout: true
flow.ci_1   | 2018-02-26 06:56:41.677 [TRACE] TaskConfig - Cmd.Toggle.ExecutionTimeout: true
flow.ci_1   | 2018-02-26 06:56:41.678 [TRACE] TaskConfig - Mos.Toggle.Clean: true
flow.ci_1   | 2018-02-26 06:56:41.704 [TRACE] AgentConfig - AgentSettings{agentPath=null, webSocketUrl='ws://127.0.0.1:8080/flow-api/agent/cmd/logging', cmdStatusUrl='http://127.0.0.1:8080/flow-control-center/cmd/report', cmdLogUrl='http://127.0.0.1:8080/flow-control-center/cmd/log/upload', zookeeperUrl='127.0.0.1:2181'} com.flow.platform.domain.AgentSettings@5f11c337
flow.ci_1   | 26-Feb-2018 06:56:42.643 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployWAR Deployment of web application archive [/usr/local/tomcat/webapps/flow-control-center.war] has finished in [9,805] ms
flow.ci_1   | 26-Feb-2018 06:56:42.684 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployWAR Deploying web application archive [/usr/local/tomcat/webapps/flow-api.war]
flow.ci_1   | 2018-02-26 06:56:42.720 [TRACE] CmdDispatchService:checkTimeoutTask - start
flow.ci_1   | 2018-02-26 06:56:42.744 [TRACE] ZoneService - Root zookeeper node initialized: /flow-agents
flow.ci_1   | 2018-02-26 06:56:42.815 [TRACE] ZoneService - Zone node initialized: /flow-agents/default
flow.ci_1   | 2018-02-26 06:56:42.818 [TRACE] AbstractContextInitHandler - zoneServiceImpl started
flow.ci_1   | 2018-02-26 06:56:42.823 [TRACE] AbstractContextInitHandler - zooKeeperServiceImpl started
flow.ci_1   | 2018-02-26 06:56:42.832 [TRACE] AbstractContextInitHandler - cmdQueue started
flow.ci_1   | 2018-02-26 06:56:42.842 [TRACE] AbstractContextInitHandler - cmdStatusQueue started
flow.ci_1   | 2018-02-26 06:56:43.314 [TRACE] CmdDispatchService:checkTimeoutTask - end
flow.ci_1   | 26-Feb-2018 06:56:47.863 INFO [localhost-startStop-1] org.apache.jasper.servlet.TldScanner.scanJars At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
flow.ci_1   | SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
flow.ci_1   | SLF4J: Defaulting to no-operation (NOP) logger implementation
flow.ci_1   | SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
docker_flow.ci_1 exited with code 143

**Comment by MagicMashRoom** [comment]
还有就是我的本地的flow.ci使用admin账号登录不上去

**Comment by yunheli** [comment]
@MagicMashRoom flow.ci的docker退出了，所以登录不上去，你尝试把export CATALINA_OPTS="-Xms1536m -Xmx1536m"改的小点  Xms1g Xmx1g 试试

**Comment by MagicMashRoom** [comment]
请问export CATALINA_OPTS="-Xms1536m -Xmx1536m"，这句在哪个文件下

**Comment by yunheli** [comment]
start_services.sh

**Comment by yunheli** [comment]
你机器的内存是多少？什么机器

**Comment by MagicMashRoom** [comment]
Dell Latitude Windows 内存16G

**Comment by yunheli** [comment]
应该不是堆的问题，会看docker的日志么？flow.ci docker的日志

**Comment by MagicMashRoom** [comment]
Starting MariaDB database server: mysqld ..
mysql is up
ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: NO)
running migration
Flyway 4.2.0 by Boxfuse
2018-02-26T08:36:49.570704100Z 
Database: jdbc:mysql://127.0.0.1:3306/flow_api_db (MySQL 10.1)
Successfully validated 3 migrations (execution time 00:00.032s)
Current version of schema `flow_api_db`: 1.3
Schema `flow_api_db` is up to date. No migration necessary.
Flyway 4.2.0 by Boxfuse
2018-02-26T08:36:50.247263200Z 
Database: jdbc:mysql://127.0.0.1:3306/flow_cc_db (MySQL 10.1)
Successfully validated 2 migrations (execution time 00:00.027s)
Current version of schema `flow_cc_db`: 1.1
Schema `flow_cc_db` is up to date. No migration necessary.
finish migration
Starting Docker: docker.
26-Feb-2018 08:36:52.549 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server version:        Apache Tomcat/8.5.16
26-Feb-2018 08:36:52.553 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server built:          Jun 21 2017 17:01:09 UTC
26-Feb-2018 08:36:52.553 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server number:         8.5.16.0
26-Feb-2018 08:36:52.555 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log OS Name:               Linux
26-Feb-2018 08:36:52.555 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log OS Version:            4.9.60-linuxkit-aufs
26-Feb-2018 08:36:52.556 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Architecture:          amd64
26-Feb-2018 08:36:52.556 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Java Home:             /usr/lib/jvm/java-8-openjdk-amd64/jre
26-Feb-2018 08:36:52.557 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log JVM Version:           1.8.0_151-8u151-b12-1~deb9u1-b12
26-Feb-2018 08:36:52.557 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log JVM Vendor:            Oracle Corporation
26-Feb-2018 08:36:52.557 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log CATALINA_BASE:         /usr/local/tomcat
26-Feb-2018 08:36:52.558 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log CATALINA_HOME:         /usr/local/tomcat
26-Feb-2018 08:36:52.558 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.util.logging.config.file=/usr/local/tomcat/conf/logging.properties
26-Feb-2018 08:36:52.558 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager
26-Feb-2018 08:36:52.559 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djdk.tls.ephemeralDHKeySize=2048
26-Feb-2018 08:36:52.559 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.protocol.handler.pkgs=org.apache.catalina.webresources
26-Feb-2018 08:36:52.559 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Xms1024m
26-Feb-2018 08:36:52.559 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Xmx1024m
26-Feb-2018 08:36:52.559 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcatalina.base=/usr/local/tomcat
26-Feb-2018 08:36:52.559 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcatalina.home=/usr/local/tomcat
26-Feb-2018 08:36:52.560 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.io.tmpdir=/usr/local/tomcat/temp
26-Feb-2018 08:36:52.562 INFO [main] org.apache.catalina.core.AprLifecycleListener.lifecycleEvent Loaded APR based Apache Tomcat Native library [1.2.12] using APR version [1.5.2].
26-Feb-2018 08:36:52.563 INFO [main] org.apache.catalina.core.AprLifecycleListener.lifecycleEvent APR capabilities: IPv6 [true], sendfile [true], accept filters [false], random [true].
26-Feb-2018 08:36:52.563 INFO [main] org.apache.catalina.core.AprLifecycleListener.lifecycleEvent APR/OpenSSL configuration: useAprConnector [false], useOpenSSL [true]
26-Feb-2018 08:36:52.584 INFO [main] org.apache.catalina.core.AprLifecycleListener.initializeSSL OpenSSL successfully initialized [OpenSSL 1.1.0f  25 May 2017]
26-Feb-2018 08:36:52.798 INFO [main] org.apache.coyote.AbstractProtocol.init Initializing ProtocolHandler ["http-nio-8080"]
26-Feb-2018 08:36:52.861 INFO [main] org.apache.tomcat.util.net.NioSelectorPool.getSharedSelector Using a shared selector for servlet write/read
26-Feb-2018 08:36:52.867 INFO [main] org.apache.coyote.AbstractProtocol.init Initializing ProtocolHandler ["ajp-nio-8009"]
26-Feb-2018 08:36:52.869 INFO [main] org.apache.tomcat.util.net.NioSelectorPool.getSharedSelector Using a shared selector for servlet write/read
26-Feb-2018 08:36:52.871 INFO [main] org.apache.catalina.startup.Catalina.load Initialization processed in 1182 ms
26-Feb-2018 08:36:52.945 INFO [main] org.apache.catalina.core.StandardService.startInternal Starting service [Catalina]
26-Feb-2018 08:36:52.946 INFO [main] org.apache.catalina.core.StandardEngine.startInternal Starting Servlet Engine: Apache Tomcat/8.5.16
26-Feb-2018 08:36:52.998 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployWAR Deploying web application archive [/usr/local/tomcat/webapps/flow-control-center.war]
26-Feb-2018 08:36:56.591 INFO [localhost-startStop-1] org.apache.jasper.servlet.TldScanner.scanJars At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
2018-02-26 08:36:57.134 [TRACE] AppInit - Initializing Flow Control Center for Apache Tomcat/8.5.16
log4j:WARN No appenders could be found for logger (org.springframework.web.context.support.StandardServletEnvironment).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
2018-02-26 08:37:00.199 [TRACE] QueueConfig - Host: amqp://localhost:5672
2018-02-26 08:37:00.204 [TRACE] QueueConfig - Management Host: http://localhost:15672
2018-02-26 08:37:00.205 [TRACE] QueueConfig - Cmd queue name: flow-cmd-queue-default
2018-02-26 08:37:00.206 [TRACE] QueueConfig - Cmd RabbitMQ enabled: false
2018-02-26 08:37:00.210 [TRACE] QueueConfig - Cmd queue retry enabled: false
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
2018-02-26 08:37:05.281 [TRACE] QueueConfig - Apply in memory queue for cmd queue
2018-02-26 08:37:05.332 [TRACE] ZooKeeper - Host: 127.0.0.1:2181
2018-02-26 08:37:05.332 [TRACE] ZooKeeper - Root node: flow-agents
2018-02-26 08:37:05.332 [TRACE] ZooKeeper - Zones: default
2018-02-26 08:37:05.332 [TRACE] ZooKeeper - Embedded enabled: true
2018-02-26 08:37:05.368 [INFO ] ZooKeeper - Starting internal zookeeper server.......
2018-02-26 08:37:05.661 [INFO ] ZooKeeper - Client been connected at: 127.0.0.1:2181
2018-02-26 08:37:05.715 [TRACE] TaskConfig - Zone.Toggle.KeepIdleAgent: false
2018-02-26 08:37:05.716 [TRACE] TaskConfig - Agent.Toggle.SessionTimeout: true
2018-02-26 08:37:05.716 [TRACE] TaskConfig - Cmd.Toggle.ExecutionTimeout: true
2018-02-26 08:37:05.716 [TRACE] TaskConfig - Mos.Toggle.Clean: true
2018-02-26 08:37:05.752 [TRACE] AgentConfig - AgentSettings{agentPath=null, webSocketUrl='ws://127.0.0.1:8080/flow-api/agent/cmd/logging', cmdStatusUrl='http://127.0.0.1:8080/flow-control-center/cmd/report', cmdLogUrl='http://127.0.0.1:8080/flow-control-center/cmd/log/upload', zookeeperUrl='127.0.0.1:2181'} com.flow.platform.domain.AgentSettings@73ea1c67
26-Feb-2018 08:37:07.180 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployWAR Deployment of web application archive [/usr/local/tomcat/webapps/flow-control-center.war] has finished in [14,181] ms
26-Feb-2018 08:37:07.186 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployWAR Deploying web application archive [/usr/local/tomcat/webapps/flow-api.war]
2018-02-26 08:37:07.236 [TRACE] CmdDispatchService:checkTimeoutTask - start
2018-02-26 08:37:07.332 [TRACE] ZoneService - Root zookeeper node initialized: /flow-agents
2018-02-26 08:37:07.433 [TRACE] ZoneService - Zone node initialized: /flow-agents/default
2018-02-26 08:37:07.443 [TRACE] AbstractContextInitHandler - zoneServiceImpl started
2018-02-26 08:37:07.444 [TRACE] AbstractContextInitHandler - zooKeeperServiceImpl started
2018-02-26 08:37:07.463 [TRACE] AbstractContextInitHandler - cmdQueue started
2018-02-26 08:37:07.475 [TRACE] AbstractContextInitHandler - cmdStatusQueue started
2018-02-26 08:37:07.997 [TRACE] CmdDispatchService:checkTimeoutTask - end
26-Feb-2018 08:37:14.963 INFO [localhost-startStop-1] org.apache.jasper.servlet.TldScanner.scanJars At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
2018-02-26 08:37:17.131 [TRACE] AgentService:sessionTimeoutTask - start
2018-02-26 08:37:17.245 [TRACE] AgentService:sessionTimeoutTask - end
2018-02-26 08:37:24.353 [TRACE] AppConfig - PlatformURL{cmdUrl='http://127.0.0.1:8080/flow-control-center/cmd/send', queueUrl='http://127.0.0.1:8080/flow-control-center/cmd/queue/send', agentUrl='http://127.0.0.1:8080/flow-control-center/agents/list', agentSettingsUrl='http://127.0.0.1:8080/flow-control-center/agents/settings', agentDeleteUrl='http://127.0.0.1:8080/flow-control-center/agents/delete', agentFindUrl='http://127.0.0.1:8080/flow-control-center/agents/find', sysInfoUrl='http://127.0.0.1:8080/flow-control-center/sys/info', sysIndexUrl='http://127.0.0.1:8080/flow-control-center/index', agentCreateUrl='http://127.0.0.1:8080/flow-control-center/agents/create', cmdDownloadLogUrl='http://127.0.0.1:8080/flow-control-center/cmd/log/download'}
2018-02-26 08:37:25.786 [TRACE] PluginDao - Plugin data been loaded from path: /root/flow-ci/git-repos/plugin_cache.json
2018-02-26 08:37:25.845 [TRACE] SyncService - Start to init agent list in thread: async-task-2
26-Feb-2018 08:37:28.945 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployWAR Deployment of web application archive [/usr/local/tomcat/webapps/flow-api.war] has finished in [21,758] ms
26-Feb-2018 08:37:28.953 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deploying web application directory [/usr/local/tomcat/webapps/manager]
2018-02-26 08:37:28.993 [TRACE] PluginService:scheduleRefreshCache - Start Refresh Cache
2018-02-26 08:37:29.048 [TRACE] AbstractContextInitHandler - nodeCrontabServiceImpl started
2018-02-26 08:37:29.049 [TRACE] AbstractContextInitHandler - ymlServiceImpl started
26-Feb-2018 08:37:29.058 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deployment of web application directory [/usr/local/tomcat/webapps/manager] has finished in [105] ms
26-Feb-2018 08:37:29.058 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deploying web application directory [/usr/local/tomcat/webapps/host-manager]
2018-02-26 08:37:29.078 [TRACE] AbstractContextInitHandler - jobNumberInit started
26-Feb-2018 08:37:29.117 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deployment of web application directory [/usr/local/tomcat/webapps/host-manager] has finished in [59] ms
26-Feb-2018 08:37:29.117 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deploying web application directory [/usr/local/tomcat/webapps/docs]
26-Feb-2018 08:37:29.142 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deployment of web application directory [/usr/local/tomcat/webapps/docs] has finished in [25] ms
26-Feb-2018 08:37:29.151 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deploying web application directory [/usr/local/tomcat/webapps/examples]
26-Feb-2018 08:37:29.741 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deployment of web application directory [/usr/local/tomcat/webapps/examples] has finished in [599] ms
26-Feb-2018 08:37:29.741 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deploying web application directory [/usr/local/tomcat/webapps/ROOT]
26-Feb-2018 08:37:30.201 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deployment of web application directory [/usr/local/tomcat/webapps/ROOT] has finished in [460] ms
26-Feb-2018 08:37:30.235 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["http-nio-8080"]
26-Feb-2018 08:37:30.303 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["ajp-nio-8009"]
26-Feb-2018 08:37:30.313 INFO [main] org.apache.catalina.startup.Catalina.start Server startup in 37442 ms
2018-02-26 08:37:30.833 [TRACE] AbstractContextInitHandler - userRoleInit started
2018-02-26 08:37:30.907 [TRACE] AbstractContextInitHandler - cmdCallbackQueue started
2018-02-26 08:37:30.943 [TRACE] ContextInitHandler - 
 _____  _                    ____  _   ____   _                 _              _   ____                                      
|  ___|| |  ___  __      __ / ___|(_) / ___| | |_   __ _  _ __ | |_   ___   __| | / ___|  _   _   ___   ___   ___  ___  ___  
| |_   | | / _ \ \ \ /\ / /| |    | | \___ \ | __| / _` || '__|| __| / _ \ / _` | \___ \ | | | | / __| / __| / _ \/ __|/ __| 
|  _|  | || (_) | \ V  V / | |___ | |  ___) || |_ | (_| || |   | |_ |  __/| (_| |  ___) || |_| || (__ | (__ |  __/\__ \\__ \ 
|_|    |_| \___/   \_/\_/   \____||_| |____/  \__| \__,_||_|    \__| \___| \__,_| |____/  \__,_| \___| \___| \___||___/|___/ 
                                                                                                                             
2018-02-26T08:37:30.943961900Z

**Comment by yunheli** [comment]
启动了啊

**Comment by MagicMashRoom** [comment]
对啊 就是启动了  但是在网页上点击登录没有任何反应

**Comment by yunheli** [comment]
http://127.0.0.1:8080/flow-api/index 这个能访问么？

**Comment by yunheli** [comment]
端口没被占用吧

**Comment by MagicMashRoom** [comment]
没有 3000端口没有用过

**Comment by MagicMashRoom** [comment]
加个QQ吧 GitHub交流好麻烦

**Comment by yunheli** [comment]
1059103388
