### ISSUE TITLE
condition下边不支持用系统变量吗？

### ISSUE THREAD

**Issue by ysnows** [FlowCI/docs#33]
![image](https://user-images.githubusercontent.com/11255869/38597239-071414f2-3d89-11e8-93f8-7f06051c4e2e.png)

**Comment by yang-guo-2016** [comment]
@ysnows 支持的, FLOW_GIT_BRANCH == 'master' 不用加 ${}

**Comment by ysnows** [comment]
谢谢啦 @yang-guo-2016
