### ISSUE TITLE
钉钉通知

### ISSUE THREAD

**Issue by LockheedQi** [FlowCI/docs#35]
请问是否有钉钉通知配置的文档啊,目前支持钉钉通知吗

**Comment by yunheli** [comment]
@LockHeedQi 暂时没有

**Comment by yunheli** [comment]
@LockHeedQi 可以自己写个curl来做这件事 https://open-doc.dingtalk.com/docs/doc.htm?treeId=257&articleId=105735&docType=1

**Comment by yunheli** [comment]
@LockHeedQi curl -X POST \
  'https://oapi.dingtalk.com/robot/send?access_token=xxx' \
  -H 'cache-control: no-cache' \
  -H 'content-type: application/json' \
  -H 'postman-token: 789ba550-fc7b-7437-701f-686969eda101' \
  -d '{
     "msgtype": "text",
     "text": {
         "content": "我就是我,  @1825718XXXX 是不一样的烟火"
     }
}'

**Comment by yunheli** [comment]
新建一个 Step 贴上上面的code来做吧

**Comment by yunheli** [comment]
```
curl -X POST \
  'https://oapi.dingtalk.com/robot/send?access_token=xxxx' \
  -H 'cache-control: no-cache' \
  -H 'content-type: application/json' \
  -H 'postman-token: 789ba550-fc7b-7437-701f-686969eda101' \
  -d '{
     "msgtype": "text",
     "text": {
         "content": "我就是我,  @1825718XXXX 是不一样的烟火"
     }
}'
```

**Comment by LockHeedQi** [comment]
感谢!已经配置好.还有个疑问,就是这个content如何传入环境变量的值呢?比如我想发出个$APP_NAME 构建成功!,我刚刚试了${APP_NAME} 貌似并不行.

**Comment by yunheli** [comment]
```
echo "curl -X POST \
  'https://oapi.dingtalk.com/robot/send?access_token=xxx' \
  -H 'cache-control: no-cache' \
  -H 'content-type: application/json' \
  -H 'postman-token: 215d1765-aed3-f010-815d-91996e2ed820' \
  -d '{
     "msgtype": \"text\",
     "text": {
         "content": \"${app_name} 我就是我,  @1825718XXXX 是不一样的烟火\"
     }
}'" | sh
```
