### ISSUE TITLE
gitlab分支上push怎么自动触发构建?

### ISSUE THREAD

**Issue by iBoCoding** [FlowCI/docs#41]
gitlab分支上push怎么不触发构建呢,怎么自动触发构建?

**Comment by yang-guo-2016** [comment]
@iBoCoding gitlab 的项目中添加 webhook 了嘛？

**Comment by iBoCoding** [comment]
![image](https://user-images.githubusercontent.com/20784707/40531916-578fee32-6030-11e8-8c87-a154e111a8c1.png)
添加了

**Comment by iBoCoding** [comment]
已解决,ip是127.0.0.1改下就好了,谢谢
