### ISSUE TITLE
安装后无法登陆

### ISSUE THREAD

**Issue by zetterma** [FlowCI/docs#50]
config: Object
description: "Network Error"
message: "Network Error"

request: Object
response: undefined
stack: "Error: Network Error at e.exports (http://192.168.2.234:3000/main.edce124db8e9eba9278b.js:1:157928) at p.onerror (http://192.168.2.234:3000/main.edce124db8e9eba9278b.js:1:156726)"

__proto__: Object

**Comment by bruceqiao** [comment]
同无法登陆（安装后默认的 admin  123456）
