### ISSUE TITLE
 MacOS

### ISSUE THREAD

**Issue by MRZHL** [FlowCI/docs#6]
I want to build it base on MacOS , but  there are no docs

**Comment by zhenlove** [comment]
可是使用Docker for Mac 来安装 @MRZHL

**Comment by yunheli** [comment]
@MRZHL  现在可以基于docker安装 https://github.com/FlowCI/docs/blob/master/cf_docker.md 在mac上，随后会上线采用brew install 方式安装到mac机器上，敬请期待
