### ISSUE TITLE
无限重连8080端口

### ISSUE THREAD

**Issue by xiao1wen2** [FlowCI/docs#71]
您好，这个部署好后 初始化创建用户名后 操作几秒会不断重新去连接8080端口  是为什么呀？

**Comment by gy2006** [comment]
后端是 8080 端口，一般后端服务断开的话会尝试重新连接，可以看一下浏览器的网络请求吗？

**Comment by xiao1wen2** [comment]
![image](https://user-images.githubusercontent.com/31750694/110609586-5554df80-81c8-11eb-8cea-fa9d2532f7b2.png)

**Comment by xiao1wen2** [comment]
![image](https://user-images.githubusercontent.com/31750694/110609853-9baa3e80-81c8-11eb-9831-037b0ba7a9c2.png)

**Comment by xiao1wen2** [comment]
> 后端是 8080 端口，一般后端服务断开的话会尝试重新连接，可以看一下浏览器的网络请求吗？

我看服务是正常跑着的

**Comment by gy2006** [comment]
这个应错误应该是没有连接到服务器

可以尝试一下能否用浏览器打 `http://192.168.221.50:8080` ，如果不能打开的话说明服务器还没有完全起来，可以看一下 flow-core docker 里的 log。

这种现象通常的问题 flow.ci 需要从 github 取一些模板和插件的数据，但是 github 访问不了

**Comment by xiao1wen2** [comment]
> 这个应错误应该是没有连接到服务器
> 
> 可以尝试一下能否用浏览器打 `http://192.168.221.50:8080` ，如果不能打开的话说明服务器还没有完全起来，可以看一下 flow-core docker 里的 log。
> 
> 这种现象通常的问题 flow.ci 需要从 github 取一些模板和插件的数据，但是 github 访问不了

我昨天又看了一下 flow-core确实又挂了 没起来。 这个能不能离线操作  是一定需要联网才能做后续操作，是吗？

**Comment by gy2006** [comment]
目前是这样的，现在所有的模板插件都在 github 上，所以启动时需要从 github 上获取最新的模板和插件。

**Comment by xiao1wen2** [comment]
> 目前是这样的，现在所有的模板插件都在 github 上，所以启动时需要从 github 上获取最新的模板和插件。

**Comment by xiao1wen2** [comment]
> 目前是这样的，现在所有的模板插件都在 github 上，所以启动时需要从 github 上获取最新的模板和插件。

哦哦  好的  谢谢！！后续会不会考虑把这些放到容器 或做成离线的包？？

**Comment by gy2006** [comment]
不客气！这个不是很复杂，下个版本会把这个功能加进去
