### ISSUE TITLE
[Help wanted] Configuration as code

### ISSUE THREAD

**Issue by SlausB** [FlowCI/docs#72]
Hello! At first, I wanna thank you for the awesome project!
I'm wondering if is it possible to specify users, credentials, pipelines, jobs, tasks, etc. in some human-readable file to be stored in SCM? I tried to reverse-engineer `FlowCI` a bit and suspect that it all stored within `MongoDB` - am I right? Is there a way to maybe bootstrap `FlowCI` with initial configuration from human-readable files through some API?

**Comment by gy2006** [comment]
Thanks, these credentials, jobs and etc all stored in a database, cannot be stored in SCM at moment. 
This is a good idea if bootstrap with some initial configuration files, I'll think about it in the next release.
